services:
  - type: web
    name: findmybizname
    env: node
    plan: free
    runtime: node
    nodeVersion: "20"
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
